# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\x12\ninventario\"\x1f\n\x11SolicitudProducto\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x01\x32T\n\nInventario\x12\x46\n\x0fObtenerProducto\x12\x1d.inventario.SolicitudProducto\x1a\x14.inventario.Productob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOLICITUDPRODUCTO._serialized_start=32
  _SOLICITUDPRODUCTO._serialized_end=63
  _PRODUCTO._serialized_start=65
  _PRODUCTO._serialized_end=119
  _INVENTARIO._serialized_start=121
  _INVENTARIO._serialized_end=205
# @@protoc_insertion_point(module_scope)
